# Generated by Django 3.2.7 on 2021-09-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_auto_20210916_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='owner',
            new_name='author',
        ),
    ]
